### Introduction

The goal of this notebook is to perform EDA analysis on our variables that predict sunset quality. I am currently working in a self labled data set that targets rating which will be predicted using the variables, `date`, `sunset_time`, `rating_source`, `cloud_cover`,
       `cloud_cover_low`, `cloud_cover_mid`, `cloud_cover_high`, `humidity`, `visibility`, `temperature`, `wind_speed`, `created_at`.

In [35]:
import sqlite3
import pandas as pd
import matplotlib as plt
import numpy as np

In [36]:
conn = sqlite3.connect(r"C:\Users\ed4er\sunset-predictor\sunset.db") #connect to db
df = pd.read_sql_query("SELECT * FROM sunset_ratings", conn) #create dataframe out of sql query
df1 = pd.read_sql_query("SELECT * FROM weather_logs", conn)
conn.close()

In [37]:
df.columns

Index(['id', 'date', 'sunset_time', 'rating', 'rating_source', 'cloud_cover',
       'cloud_cover_low', 'cloud_cover_mid', 'cloud_cover_high', 'humidity',
       'visibility', 'temperature', 'wind_speed', 'created_at'],
      dtype='str')

In [43]:
df1.head()

,id,timestamp,sunset_time,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,humidity,visibility,temperature,wind_speed
0,1,2026-02-15T16:00:22.497314,2026-02-15T17:48:47.493896-08:00,84.0,84.0,76.0,0.0,88.0,15000.0,12.5,12.6
1,2,2026-02-16T11:11:54.683443,2026-02-16T17:49:51.830313-08:00,100.0,100.0,100.0,0.0,91.0,13100.0,8.7,6.0
2,4,2026-02-17T12:09:04.003469,2026-02-17T17:50:55.862826-08:00,98.0,66.0,98.0,0.0,84.0,16800.0,7.1,18.1
3,5,2026-02-18T12:59:26.320789,2026-02-18T17:51:59.584910-08:00,100.0,8.0,100.0,0.0,75.0,22000.0,7.4,8.7
4,6,2026-02-19T14:48:59.680660,2026-02-19T17:53:02.991241-08:00,0.0,0.0,0.0,0.0,73.0,22800.0,7.0,16.9

In [40]:
df1["timestamp"].duplicated().sum()

np.int64(0)

In [32]:
df["date"].duplicated().sum()

np.int64(0)

In [47]:
df1['date'] = pd.to_datetime(df1['timestamp']).dt.date

df1.head()

,id,timestamp,sunset_time,cloud_cover,cloud_cover_low,cloud_cover_mid,cloud_cover_high,humidity,visibility,temperature,wind_speed,date
0,1,2026-02-15T16:00:22.497314,2026-02-15T17:48:47.493896-08:00,84.0,84.0,76.0,0.0,88.0,15000.0,12.5,12.6,2026-02-15
1,2,2026-02-16T11:11:54.683443,2026-02-16T17:49:51.830313-08:00,100.0,100.0,100.0,0.0,91.0,13100.0,8.7,6.0,2026-02-16
2,4,2026-02-17T12:09:04.003469,2026-02-17T17:50:55.862826-08:00,98.0,66.0,98.0,0.0,84.0,16800.0,7.1,18.1,2026-02-17
3,5,2026-02-18T12:59:26.320789,2026-02-18T17:51:59.584910-08:00,100.0,8.0,100.0,0.0,75.0,22000.0,7.4,8.7,2026-02-18
4,6,2026-02-19T14:48:59.680660,2026-02-19T17:53:02.991241-08:00,0.0,0.0,0.0,0.0,73.0,22800.0,7.0,16.9,2026-02-19

In [48]:
df1.duplicated().sum()

np.int64(0)